name: Deploy Lambda Test Function

on:
  push:
    branches:
      - master-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Configurar versión de Python
      run: echo "PYTHON_VERSION=python3.12" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        cd lambdas_functions/bank_core/BankCoreJwtTesting
        mkdir -p package
        pip install -r requirements.txt -t package

    - name: Package lambda with dependencies
      run: |
        cd lambdas_functions/bank_core/BankCoreJwtTesting
        cd package && zip -r ../BankCoreJwtTesting.zip . && cd ..
        zip -g BankCoreJwtTesting.zip *.py

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Create Lambda
      run: |
        aws lambda create-function \
        --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME_010 }} \
        --runtime python3.12 \
        --role ${{ secrets.LAMBDA_ROLE_STANDARD_NAME }} \
        --handler lambda_function.lambda_handler \
        --timeout 30 \
        --memory-size 128 \
        --zip-file fileb://lambdas_functions/bank_core/BankCoreJwtTesting/BankCoreJwtTesting.zip

    #- name: Deploy Lambda BankCoreJwtTesting
    #  run: |
    #    aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME_010 }} --zip-file fileb://lambdas_functions/bank_core/BankCoreJwtTesting.zip