name: Deploy Lambda Test Function

on:
  push:
    branches:
      - master-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      
      - name: Configurar versión de Python
        run: echo "PYTHON_VERSION=python3.12" >> $GITHUB_ENV

      # Usamos Amazon Linux 2023 para construir las dependencias en un entorno compatible con Python 3.12
      - name: Build package in Amazon Linux 2023 container
        run: |
          docker run --rm \
            -v "$PWD/lambdas_functions/bank_core/BankCoreJwtTesting":/var/task \
            -w /var/task \
            amazonlinux:2023 bash -c "\
              dnf update -y && \
              dnf install -y python3.12 python3.12-devel gcc openssl-devel libffi-devel && \
              python3.12 -m ensurepip && \
              python3.12 -m pip install --upgrade pip && \
              mkdir -p package && \
              python3.12 -m pip install -r requirements.txt -t package"


      # Empaquetamos el código y las dependencias
      - name: Package lambda with dependencies
        run: |
          cd lambdas_functions/bank_core/BankCoreJwtTesting
          cd package && zip -r ../BankCoreJwtTesting.zip . && cd ..
          zip -g BankCoreJwtTesting.zip *.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create Lambda
        run: |
          aws lambda create-function \
            --function-name ${{ secrets.AWS_LAMBDA_FUNCTION_NAME_010 }} \
            --runtime python3.12 \
            --role ${{ secrets.LAMBDA_ROLE_STANDARD_NAME }} \
            --handler lambda_function.lambda_handler \
            --timeout 30 \
            --memory-size 128 \
            --zip-file fileb://lambdas_functions/bank_core/BankCoreJwtTesting/BankCoreJwtTesting.zip
